[package]
org = "wso2"
name = "health.fhir.r4.davincidrug.basic"
version = "1.0.0"
distribution = "2201.8.1"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "Basic", "r4", "health.fhir.r4.davincidrug"]
template = true
