[package]
org = "wso2"
name = "health.fhir.r4.carinbb200.explanationofbenefit"
version = "1.0.0"
distribution = "2201.10.2"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "ExplanationOfBenefit", "r4", "health.fhir.r4.carinbb200"]
template = true
