[package]
org = "wso2"
name = "health.fhir.r4.davinciplannet.insuranceplan"
version = "1.0.0"
distribution = "2201.10.2"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "InsurancePlan", "r4", "health.fhir.r4.davinciplannet"]
template = true
