[package]
org = "wso2"
name = "health.fhir.r4.uscore700.diagnosticreport"
version = "1.0.0"
distribution = "2201.12.3"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "DiagnosticReport", "r4", "health.fhir.r4.uscore700"]
template = true
