[package]
authors = ["Ballerina"]
distribution = "2201.10.2"
keywords = ["Healthcare", "FHIR", "HealthcareService", "r4", "health.fhir.r4.davinciplannet"]
name = "health.fhir.r4.davinciplannet.healthcareservice"
org = "wso2"
template = true
version = "1.0.0"
