[package]
org = "healthcare"
name = "health.fhir.r4.davincidrug.medicationknowledge"
version = "1.0.0"
distribution = "2201.10.2"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "MedicationKnowledge", "r4", "health.fhir.r4.davincidrug"]
template = true
