openapi: 3.0.1
info:
  title: Metrics API
  description: API to retrieve application metrics.
servers:
  - url: http://localhost:9797/
paths:
  /metrics:
    get:
      summary: Get application metrics
      responses:
        '200':
          description: Successful response with metrics data
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: OK
                  metrics:
                    type: object
                    additionalProperties:
                      type: number
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
      tags:
        - metrics