[package]
org = "wso2"
name = "patient.api"
version = "1.0.0"
distribution = "2201.12.3"
keywords = ["Healthcare", "FHIR", "Patient", "r4", "health.fhir.r4.uscore501"]

[build-options]
observabilityIncluded = true

# [[dependency]]
# org="ballerinax"
# name="health.fhirr4"
# version="2.0.3"
# repository="local"
